### ISSUE TITLE
java.lang.IllegalArgumentException: 26 is not a valid line for pointer

### ISSUE THREAD

**Issue by jasminpethani** [Backelite/sonar-swift#96] opened 2017-08-08 05:03 UTC
Getting this error after running  run-sonar-swift.sh 
i have disabled slather from  run-sonar-swift.sh using SonarQube Server 6.3.1 and swift plugin version 0.3.4

Need a solution

```
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalArgumentException: 26 is not a valid line for pointer. File [moduleKey=XYZ, relative=XYZ/ABCLabel.swift, basedir=/Users/xyz/Desktop/XYZ] has 20 line(s)
	at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:249)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:186)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.selectLine(DefaultInputFile.java:209)
	at org.sonar.scanner.issue.DeprecatedIssueBuilderWrapper.line(DeprecatedIssueBuilderWrapper.java:59)
	at org.sonar.plugins.swift.issues.swiftlint.SwiftLintReportParser.recordIssue(SwiftLintReportParser.java:98)
	at org.sonar.plugins.swift.issues.swiftlint.SwiftLintReportParser.parseReport(SwiftLintReportParser.java:62)
	at org.sonar.plugins.swift.issues.swiftlint.SwiftLintSensor.parseReportIn(SwiftLintSensor.java:79)
	at org.sonar.plugins.swift.issues.swiftlint.SwiftLintSensor.analyse(SwiftLintSensor.java:65)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
ERROR - Command 'sonar-scanner ' failed with error code: 1
```

**Comment by zippy1978** [comment] 2017-08-21 16:27
Hi @jasminpethani,

Could you try again with the latest release (0.3.5) ?
Now you can also update slather : it will run fine (I tested with slather 2.4.2).

**Comment by sorinant** [comment] 2017-11-17 10:34
I have the same issue with v 0.3.5 and slather 2.4.3. Is there a way we can fix it?

12:26:19.051 INFO: SonarQube Scanner 3.0.3.778
12:26:19.057 INFO: Java 1.8.0_131 Oracle Corporation (64-bit)
12:26:19.057 INFO: Mac OS X 10.12.6 x86_64
12:26:19.057 INFO: Slather 2.4.3
12:26:21.890 DEBUG: Plugins:
12:26:21.891 DEBUG:   * Swift (Backelite) 0.3.5 (backelitesonarswiftplugin)
12:26:21.931 INFO: SonarQube server 6.3.1
12:26:21.932 INFO: Default locale: "en_US", source code encoding: "UTF-8" (analysis is platform dependent)
12:26:32.580 ERROR: Error during SonarQube Scanner execution
java.lang.IllegalArgumentException: 180 is not a valid line for pointer. File [moduleKey=vo, relative=votest.swift, basedir=/Users/Shared/Jenkins/Home/workspace/ultibranch_feature_VOMI-950-244EUNPTM3VRVHMJQ5SCGFDDSOWUMVAUUEDWWQNDPP6AAMDJLOJA] has 178 line(s)
	at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:249)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:186)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.selectLine(DefaultInputFile.java:209)
	at org.sonar.scanner.issue.DeprecatedIssueBuilderWrapper.line(DeprecatedIssueBuilderWrapper.java:59)
	at org.sonar.plugins.swift.issues.tailor.TailorReportParser.recordIssue(TailorReportParser.java:104)
	at org.sonar.plugins.swift.issues.tailor.TailorReportParser.parseReport(TailorReportParser.java:69)
	at org.sonar.plugins.swift.issues.tailor.TailorSensor.parseReportIn(TailorSensor.java:82)
	at org.sonar.plugins.swift.issues.tailor.TailorSensor.analyse(TailorSensor.java:68)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
12:26:32.583 ERROR: 
12:26:32.583 ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
12:26:32.583 DEBUG: Execution getVersion
12:26:32.583 DEBUG: Execution stop

**Comment by gilleycro** [comment] 2018-08-29 08:19
Is there any plan to fix this ? I am getting same error in swift, so I could also help fix it

**Comment by CoreOne23** [comment] 2018-08-31 12:50
@zippy1978 The `project-swiftlint.txt` file in sonar-report folder contains warning about my appdelegate class at line no 143, but my class only have 97 lines.  This report along with lizard, trailor are creating on each sonar.sh run. But the data seems to be outdated. I cleared derived data but the data seems appearing again. Not just appdelegate. report regarding other classes are also outdated. I installed the `backelite-sonar-swift-plugin-0.4.1` and has slather version of 2.4.3.

**Comment by gaelfoppolo** [comment] 2019-08-10 11:36
Do you still face this issue with the current version of the plugin?
Can you provide a project sample to reproduce the issue?

**Comment by CoreOne23** [comment] 2019-08-10 11:50
I  didn't try it on the newer version, I will update if I face any issues.

**Comment by gaelfoppolo** [comment] 2019-08-24 12:22
Closing this issue. Please open a new one if you're experiencing this.

**Closed by gaelfoppolo** 2019-08-24 12:22 UTC
Labels: bug, waiting for feedback
