### ISSUE TITLE
LizardReportParser PersistenceMode error

### ISSUE THREAD

**Issue by chiliec** [Backelite/sonar-swift#198] opened 2019-01-10 08:29 UTC
**Describe the bug**
```sh
...
12:22:05.544 INFO: Sensor org.sonar.plugins.swift.complexity.LizardSensor [backelitesonarswiftplugin]
12:22:05.545 INFO: Processing complexity report 
12:22:05.989 INFO: ------------------------------------------------------------------------
12:22:05.990 INFO: EXECUTION FAILURE
12:22:05.990 INFO: ------------------------------------------------------------------------
12:22:05.990 INFO: Total time: 9.034s
12:22:06.066 INFO: Final Memory: 13M/156M
12:22:06.066 INFO: ------------------------------------------------------------------------
12:22:06.067 ERROR: Error during SonarQube Scanner execution
java.lang.NoClassDefFoundError: org/sonar/api/measures/PersistenceMode
	at org.sonar.plugins.swift.complexity.LizardReportParser.buildMeasureList(LizardReportParser.java:128)
	at org.sonar.plugins.swift.complexity.LizardReportParser.addComplexityFileMeasures(LizardReportParser.java:116)
	at org.sonar.plugins.swift.complexity.LizardReportParser.parseFile(LizardReportParser.java:91)
	at org.sonar.plugins.swift.complexity.LizardReportParser.parseReport(LizardReportParser.java:64)
	at org.sonar.plugins.swift.complexity.LizardSensor.parseReportsIn(LizardSensor.java:66)
	at org.sonar.plugins.swift.complexity.LizardSensor.analyse(LizardSensor.java:57)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.ClassNotFoundException: org.sonar.api.measures.PersistenceMode
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 37 more
```
**SonarQube environment:**
SonarQube Version 7.0 (build 36138)
```sh
$ sonar-scanner --version
INFO: Scanner configuration file: /usr/local/Cellar/sonar-scanner/3.3.0.1492/libexec/conf/sonar-scanner.properties
INFO: Project root configuration file: NONE
INFO: SonarQube Scanner 3.3.0.1492
INFO: Java 1.8.0_144 Oracle Corporation (64-bit)
INFO: Mac OS X 10.13.6 x86_64

$ lizard --version
1.15.7
```

**Comment by gaelfoppolo** [comment] 2019-08-10 12:43
Look like a duplicate of https://github.com/Backelite/sonar-swift/issues/118.
Can you check it out and tell us if it solves your issue?

**Comment by gaelfoppolo** [comment] 2019-08-24 12:26
Closing this issue. Please open a new one if you're experiencing this.

**Closed by gaelfoppolo** 2019-08-24 12:26 UTC
Labels: duplicate, question, waiting for feedback
