### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by LionWY** [Backelite/sonar-swift#258] opened 2019-12-12 07:41 UTC
### New Issue Checklist

- [x] Updated the plugin to the latest version 
- [x] I read the [Contribution Guidelines](https://github.com/Backelite/sonar-swift/blob/master/CONTRIBUTING.md)
- [x] I read the [documentation](https://github.com/Backelite/sonar-swift/wiki)
- [x] I searched for existing [GitHub issues](https://github.com/Backelite/sonar-swift/issues)

### Issue Description

It's very strange, when I delete lizard-report.xml, and run sonar-scanner, the result is sucess. otherwise it's failed, and the error log is "ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
	at com.backelite.sonarqube.swift.complexity.LizardReportParser.addComplexityFileMeasures(LizardReportParser.java:173)", I think it's a bug, anyone help me?

$oclint-json-compilation-database -- -report-type pmd -o sonar-reports/oclint.xml
$lizard --xml > sonar-reports/lizard-report.xml
$sonar-scanner 
result:
ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
	at com.backelite.sonarqube.swift.complexity.LizardReportParser.addComplexityFileMeasures(LizardReportParser.java:173)
	at com.backelite.sonarqube.swift.complexity.LizardReportParser.parseMeasure(LizardReportParser.java:120)
	at com.backelite.sonarqube.swift.complexity.LizardReportParser.parseFile(LizardReportParser.java:89)
	at com.backelite.sonarqube.swift.complexity.LizardReportParser.parseReport(LizardReportParser.java:69)
	at com.backelite.sonarqube.swift.complexity.LizardSensor.execute(LizardSensor.java:71)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:387)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:383)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:346)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
ERROR:

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

Sonarqube: 8.0 (community edition)
OS: macOS Catalina
SonarQube Scanner 4.2.0.1873
sonar-swift: backelite-sonar-swift-plugin-0.4.5.jar
oclint: 0.14

**Comment by LionWY** [comment] 2019-12-12 07:42
like this [253](https://github.com/Backelite/sonar-swift/issues/253)

**Comment by himanshuNetsol** [comment] 2019-12-16 11:29
Facing the exact same issue. Can anyone please help ?

**Comment by zippy1978** [comment] 2020-01-24 09:15
Hi,
The problem is related to complexity sensor trying to index data on a source file which is not located into sources or tests directories (sonar.sources and sonar.tests).

However the plugin should  not crash and only display a warning instead.

Issue is fixed on develop branch

**Closed by zippy1978** 2020-01-24 09:15 UTC
