### ISSUE TITLE
sonar-swift doesn't support sonarqube v6.2

### ISSUE THREAD

**Issue by ssheru** [Backelite/sonar-swift#68] opened 2017-02-16 12:30 UTC
We have been using open source Swift plugin for Sonarqube 5.6 and we recently upgraded to Sonarqube v6.2 and indeed this plugin is unsupported.

Can you please update these plugin to support Sonarqube v6.2.

Any help is highly appreciated.

**Comment by zippy1978** [comment] 2017-02-21 22:54
Hi, 

This is a duplicate of https://github.com/Backelite/sonar-swift/issues/61

**Closed by zippy1978** 2017-02-21 22:54 UTC

**Comment by ssheru** [comment] 2017-02-27 14:11
Thanks Zippy1978...
