### ISSUE TITLE
There should be some way to keep the swiflint rules always upto date.

### ISSUE THREAD

**Issue by singh88** [Backelite/sonar-swift#137] opened 2018-05-01 23:51 UTC
We should find a way to keep swiftlint rules always in sync with `realm/swiftlint` releases or we should find a way to give a user an option to use custom `.swiftlint yml` file and binary.

**Comment by singh88** [comment] 2018-06-07 03:20
sure @wtimme, I will take a look.

**Comment by singh88** [comment] 2018-06-13 14:50
Hey, @wtimme I read through your file and I think it will be able to read your custom swiftlint file but the problem would occur when you try to upload this data into sonarqube. Because at that point SonarQube may reject with message `Rules not found` because I have seen this in past. Its all because the sonar-swift plugin is using [rules.json](https://github.com/Backelite/sonar-swift/blob/develop/sonar-swift-plugin/src/main/resources/org/sonar/plugins/swiftlint/rules.json) to render swiftlint rules on sonarqube.

**Comment by wtimme** [comment] 2018-06-14 20:12
Hey @singh88, thanks for having a look, and thanks for your feedback!

I'm running SonarQube from a Docker image, and stumbled upon this repository while searching for a way to integrate the SwiftLint results into the CI. My current approach is to use [run-sonar-swift.sh](https://github.com/Backelite/sonar-swift/blob/develop/sonar-swift-plugin/src/main/shell/run-sonar-swift.sh) and run it whenever I want to have results in SonarQube. This worked fairly well, and I was able to specify my custom `.swiftlint.yml` without issues.

Is that the wrong approach? Is there an easier way, or am I misunderstanding the purpose of that script? I'm happy for every hint and suggestion, thanks in advance!

**Comment by gaelfoppolo** [comment] 2019-08-10 12:02
As pointed by @singh88, a problem will occur when SonarQube will analyze your results, since the `rules.json` will not have the new rules of your `.swiftlint`.
Can we close this issue?

**Comment by davidy4ng** [comment] 2019-08-20 14:00
The issue is related to the way SonarQube works with custom rules.

https://docs.sonarqube.org/latest/extend/adding-coding-rules/

As of today, it's not possible to add custom rules, those rules needs to be coded in a plugin, which is installed on your SonarQube server.
Therefore, adding custom rules will always need a plugin update.

To quote the SonarQube documentation :
> Before implementing a new coding rule, you should consider whether it is specific to your own context or might benefit others. If it might benefit others, you can propose it on the Community Forum. If there is shared interest, then it might be implemented for you directly in the related language plugin. It means less maintenance for you, and benefit to others.

I'm closing the issue.

**Closed by davidy4ng** 2019-08-20 14:00 UTC
Labels: waiting for feedback
