### ISSUE TITLE
The domain/default pair of() does not exist, Problem in passing Path with spaces

### ISSUE THREAD

**Issue by AnkitaShrivastavaImanage** [Backelite/sonar-swift#152] opened 2018-08-02 06:29 UTC
The parameters in my sonar-project.properties are 

##########################
#Required configuration#
##########################

sonar.projectKey=My Mac App
sonar.projectName=My Mac App

#Path to source directories
sonar.sources=FirstName LastName/FirstName LastName

#Scheme to build your application
sonar.swift.appScheme=FirstName LastName

#Configuration to use for your scheme. if you do not specify that the default will be Debug
sonar.swift.appConfiguration=Debug

sonar.swift.appName=FirstName LastName.app

sonar.swift.plist=iFirstName LastName/FirstName LastName/info.plist

sonar.projectVersion=1.3

#Xcode project configuration (.xcodeproj)
#and use the later to specify which project(s) to include in the analysis (comma separated list)
#Specify either xcodeproj or xcodeproj + xcworkspace
sonar.swift.project=FirstName LastName/FirstName LastName.xcodeproj
sonar.swift.workspace=My mac app.xcworkspace

#Destination Simulator to run tests
sonar.swift.simulator=platform=macOS arch:x86_64

I am getting this error

The domain/default pair of (/Users/myName/Downloads/My-Mac-App/FirstName, LastName/FirstName) does not exist
-n .
-n Running surefire

So my Questions are

1. What does The domain/default pair means, from where does it is constructing wrong path "FirstName, LastName/FirstName"  instead of "FirstName LastName/FirstName LastName" how to correct it?

**Comment by cpowell001** [comment] 2018-08-02 23:19
@AnkitaShrivastavaImanage I had a similar issue. The problem is that there are spaces in your path names that are not being escaped. Wrapping those variables in quotes should solve the issue.

**Comment by gaelfoppolo** [comment] 2019-08-10 12:12
https://github.com/Backelite/sonar-swift/pull/234 should fix this issue. Awaiting merge.

**Comment by gaelfoppolo** [comment] 2019-09-03 18:35
#246 was merged. Awaiting release.

**Closed** 2020-01-24 10:27 UTC
Labels: bug, enhancement
