### ISSUE TITLE
Build Error when executing run-sonar-swift.sh

### ISSUE THREAD

**Issue by quantumarun** [Backelite/sonar-swift#189] opened 2018-11-28 06:45 UTC
I am getting failure when executing the run-sonar-swift.sh. Code build is successful through xcode. xcpretty is installed as per instruction docs but couldn't detect. Do i need to add Provisional Profile and Certificate as well for successful execution?
Please assist.

[$] <Path>/sonar-scanner-msbuild-4.4.2.1543-net46/sonar-scanner-3.2.0.1227/bin/run-sonar-swift.sh
Running run-sonar-swift.sh...
.Extracting Xcode project information.............
<Path>/sonarqubescanner/sonar-scanner-msbuild-4.4.2.1543-net46/sonar-scanner-3.2.0.1227/bin/run-sonar-swift.sh: line 292: xcpretty: command not found
stat: compile_commands.json: stat: No such file or directory
actual = , min = 3
<Path>/sonarqubescanner/sonar-scanner-msbuild-4.4.2.1543-net46/sonar-scanner-3.2.0.1227/bin/run-sonar-swift.sh: line 300: [: -ge: unary operator expected
Running surefirexcodebuild: error: Scheme xxxxx is not currently configured for the test action.

ERROR - Command 'xcodebuild clean build test -workspace xxx.xcworkspace -scheme xxx -configuration Release -enableCodeCoverage YES -destination platform=iOS Simulator,name=iPhone X,OS=12.1 -destination-timeout 60' failed with error code: 66

**Comment by gaelfoppolo** [comment] 2018-12-24 11:19
`xcpretty` is part of the [prerequisites](https://github.com/Backelite/sonar-swift#prerequisites) and doesn't seems to be installed. 
Please [install it](https://github.com/Backelite/sonar-swift#installation-of-xcpretty-with-junit-reports-fix) and let's us know if your problem is solved.

**Comment by wenchao8023** [comment] 2018-12-28 10:59
> xcpretty

I have installed the xcpretty, but occurred the same error.

ERROR - Command 'xcodebuild clean build test -workspace MTNOP.xcworkspace -scheme MTNOP -configuration Debug -enableCodeCoverage YES -destination platform=iOS Simulator,name=iPhone 8,OS=12.1 -destination-timeout 60' failed with error code: 66.

**Comment by wenchao8023** [comment] 2018-12-28 11:12
> I am getting failure when executing the run-sonar-swift.sh. Code build is successful through xcode. xcpretty is installed as per instruction docs but couldn't detect. Do i need to add Provisional Profile and Certificate as well for successful execution?
> Please assist.
> 
> [$] /sonar-scanner-msbuild-4.4.2.1543-net46/sonar-scanner-3.2.0.1227/bin/run-sonar-swift.sh
> Running run-sonar-swift.sh...
> .Extracting Xcode project information.............
> /sonarqubescanner/sonar-scanner-msbuild-4.4.2.1543-net46/sonar-scanner-3.2.0.1227/bin/run-sonar-swift.sh: line 292: xcpretty: command not found
> stat: compile_commands.json: stat: No such file or directory
> actual = , min = 3
> /sonarqubescanner/sonar-scanner-msbuild-4.4.2.1543-net46/sonar-scanner-3.2.0.1227/bin/run-sonar-swift.sh: line 300: [: -ge: unary operator expected
> Running surefirexcodebuild: error: Scheme xxxxx is not currently configured for the test action.
> 
> ERROR - Command 'xcodebuild clean build test -workspace xxx.xcworkspace -scheme xxx -configuration Release -enableCodeCoverage YES -destination platform=iOS Simulator,name=iPhone X,OS=12.1 -destination-timeout 60' failed with error code: 66

Have you solved the problem.

**Comment by gaelfoppolo** [comment] 2018-12-28 16:36
@wenchao8023 Did you tried to execute the command itself: `xcodebuild clean build test -workspace MTNOP.xcworkspace -scheme MTNOP -configuration Debug -enableCodeCoverage YES -destination platform=iOS Simulator,name=iPhone 8,OS=12.1 -destination-timeout 60`

You can also the option `-verbose` to the command.

Please check the problem is not related to `xcodebuild` first.

**Comment by wenchao8023** [comment] 2018-12-28 23:46
My project is based on Objective-C.Then  l set "Oclint" yes, it works.




| |
郭文超
邮箱：15629120502@163.com
|

签名由 网易邮箱大师 定制

On 12/29/2018 00:36, Gaël Foppolo wrote:

@wenchao8023 Did you tried to execute the command itself: xcodebuild clean build test -workspace MTNOP.xcworkspace -scheme MTNOP -configuration Debug -enableCodeCoverage YES -destination platform=iOS Simulator,name=iPhone 8,OS=12.1 -destination-timeout 60

You can also the option -verbose to the command.

Please check the problem is not related to xcodebuild first.

**Comment by gaelfoppolo** [comment] 2018-12-29 10:54
If problem is resolved, please close the issue.

**Closed** 2019-01-04 08:43 UTC

**Comment by jzafar** [comment] 2021-02-11 13:43
I am getting same error how did you fix this. I have tried running this command 
xcodebuild clean build test -workspace MTNOP.xcworkspace -scheme MTNOP -configuration Debug -enableCodeCoverage YES -destination platform=iOS Simulator,name=iPhone 8,OS=12.1 -destination-timeout 60
This command works well. but in sonarqube when some test fails sonarqube fails.
