### ISSUE TITLE
Duplication Code not measured, any alternative solution ?

### ISSUE THREAD

**Issue by egr-ext** [Backelite/sonar-swift#244] opened 2019-08-23 11:36 UTC
The version 0.4.4 does nor measure duplication code. 

Is there a way/alternative tool to measure it ?

Regards

**Comment by gaelfoppolo** [comment] 2019-08-24 11:55
Duplicate of #188. To have the ability again, we have to add the feature. Feel free to draft a PR with a WIP of a solution.

**Closed** 2019-08-29 18:40 UTC
Labels: duplicate
